# Generated by Django 5.0.7 on 2024-08-04 17:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StickyNote',
            fields=[
                ('unid', models.UUIDField(primary_key=True,
                 serialize=False, verbose_name='Note ID')),
                ('title', models.CharField(max_length=100,
                                           verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('colors', models.JSONField(verbose_name='Colors')),
                ('create_at', models.DateTimeField(
                    default=django.utils.timezone.now,
                    verbose_name='Created At')),
                ('edited_at', models.DateTimeField(verbose_name='Edited At')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sticky Note',
                'verbose_name_plural': 'Sticky Notes',
            },
        ),
    ]
