# Generated by Django 5.0.7 on 2024-08-04 17:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StickyNotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stickynote',
            name='unid',
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True,
                serialize=False,
                verbose_name='Note ID'),
        ),
    ]
