# Generated by Django 5.0.7 on 2024-08-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StickyNotes', '0003_rename_user_stickynote_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stickynote',
            name='position',
            field=models.JSONField(verbose_name='Position'),
        ),
    ]
