# Generated by Django 5.0.7 on 2024-08-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StickyNotes', '0004_alter_stickynote_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stickynote',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='stickynote',
            name='edited_at',
            field=models.DateTimeField(
                auto_now=True, verbose_name='Edited At'),
        ),
    ]
