# Generated by Django 5.0.7 on 2024-08-04 15:38

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(
                    max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(
                    blank=True, null=True, verbose_name='last login')),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True,
                 serialize=False, unique=True, verbose_name='UUID')),
                ('user_name', models.CharField(max_length=25,
                 unique=True, verbose_name='User Name')),
                ('email', models.EmailField(max_length=254,
                 unique=True, verbose_name='E-Mail')),
                ('first_name', models.CharField(blank=True,
                 max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True,
                 max_length=50, verbose_name='Last Name')),
                ('created_at', models.DateTimeField(
                    default=django.utils.timezone.now,
                    verbose_name='Created At')),
                ('DoB', models.DateField(blank=True,
                                         verbose_name='Date of Birth')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups',
                 models.ManyToManyField(
                     blank=True,
                     help_text='The groups this user belongs to.\
                        A user will get all permissions granted \
                            to each of their groups.',
                     related_name='user_set',
                     related_query_name='user',
                     to='auth.group',
                     verbose_name='groups')),
                ('user_permissions',
                 models.ManyToManyField(blank=True,
                                        help_text='Specific permissions \
                                            for this user.',
                                        related_name='user_set',
                                        related_query_name='user',
                                        to='auth.permission',
                                        verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
