# Generated by Django 5.0.7 on 2024-08-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccounts',
         '0002_customuser_is_active_alter_customuser_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='DoB',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
    ]
