# Generated by Django 5.0.7 on 2024-08-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccounts', '0003_alter_customuser_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='DoB',
            field=models.DateField(blank=True, null=True,
                                   verbose_name='Date of Birth'),
        ),
    ]
