# Generated by Django 5.0.7 on 2024-08-04 16:16

import uuid
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccounts',
         '0005_alter_customuser_options_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4,
                                   editable=False,
                                   primary_key=True,
                                   serialize=False,
                                   unique=True,
                                   verbose_name='UUID'),
        ),
    ]
