# Generated by Django 5.0.7 on 2024-08-04 16:39

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccounts',
         '0006_alter_customuser_created_at_alter_customuser_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(
                default=False,
                verbose_name='Active Status'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(
                default=False,
                verbose_name='Staff Status'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4,
                                   primary_key=True,
                                   serialize=False,
                                   unique=True,
                                   verbose_name='UUID'),
        ),
    ]
